- hosts: all
  sudo: yes
  tasks:
    - name: Update hosts entery
      blockinfile: |
        dest=/etc/hosts backup=yes
        content='10.20.30.1 ansari.hashmap.com a1
        10.20.30.1 ansari1.hashmap.com alias1
        10.20.30.2 ansari2.hashmap.com alias2
        10.20.30.3 ansari3.hashmap.com alias3
        10.20.30.4 ansari4.hashmap.com alias4
        10.20.30.5 ansari5.hashmap.com alias5'

   - name: install ntpdate
      package:
      name: ntpdate
      state: present

 tasks:
    - name: Add repository
      yum_repository:
          name: epel
          description: EPEL YUM repo
          baseurl: https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/n/ntp-4.2.8p11-2.fc29.aarch64.rpm
          enabled: no

    - name: Install NTP daemon
      sudo: true
      yum: pkg=ntp state=present

    - name: Ensure NTP daemon autostart
      sudo: true
      service: name=ntp enabled=yes
