---
- hosts: web-servers
  tasks:
      - name: Create file
        file:
            path: /tmp/yallo
            state: touch

- hosts: web-servers
  sudo: yes
  tasks:
      - name: Create user
        user:
            name: mario
            shell: /bin/zsh

      - name: Install zlib
        yum:
            name: zlib
            state: latest
